### ISSUE TITLE
Upload transparent images using KCFinder

### ISSUE THREAD

**Issue by AndreyMyagkov** [modxcms/evolution#1247] opened 2017-02-12 18:04 UTC
When upload images in png format they are converted into jpeg. Transparent png filled with black background.
You need to add type checking pictures inot file /manager/media/browser/mcpuk/core/uploader.php

Download modified file: https://yadi.sk/d/FdwyueMe3Dx3xR

**Comment by janniconl** [comment] 2017-02-13 10:15
Duplicate of #1132 and #663

**Comment by bossloper** [comment] 2017-02-22 22:18
can close as duplicate?

**Comment by janniconl** [comment] 2017-02-27 06:55
Yes same issue.
Possible fix mentioned in #1132 and #663 (make thumbnails PNG when source is PNG or set the background to white when converting PNG to JPG). Not implemented yet though.

**Comment by dmi3yy** [comment] 2017-03-21 14:08
Close this

**Closed by dmi3yy** 2017-03-21 14:08 UTC
