### ISSUE TITLE
Cached and nested snippets not working in EVO 1.2

### ISSUE THREAD

**Issue by vinelandit** [modxcms/evolution#1089] opened 2016-12-09 14:51 UTC
a) Snippets called in [!snippetName!] format are not parsed, and just return the literal [[snippetName]] (replacing the [!!] brackets with [[]])

b) Nested snippets in alternating cached/uncached format, i.e. [!outerSnippet? &param='[[innerSnippet]]'!] are not parsed, and nested snippets using uncached format throughout throw a MySQL error.

(Backticks replaced with quotes in sample calls to avoid being marked up)

Example call:

[[Ditto? &documents='[[getVal? &docid='1' &field='featurePanel1']]' &tpl='homePanel' &extenders='summary' &truncLen='180' &truncOffset='90' ]] 

Example error (similar error occurs when the inner snippet is called in uncached format, and the whole call unparsed and returned literally when the outer snippet is in uncached format):

« MODX Parse Error »
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[[getVal?&docid=) AND sc.published=1 AND sc.deleted=0) AND (sc.privateweb=0) GRO' at line 1
SQL > SELECT DISTINCT sc.id FROM 'ajfadmin_modx'.'modx_site_content' sc LEFT JOIN 'ajfadmin_modx'.'modx_document_groups' dg on dg.document = sc.id WHERE (sc.id IN ([[getVal?&docid=) AND sc.published=1 AND sc.deleted=0) AND (sc.privateweb=0) GROUP BY sc.id
Error information	
Current Snippet	Ditto ... etc.

**Comment by modxuser** [comment] 2016-12-09 16:14
I am not a back-end Dev, but the question arises - do your custom snippets still use deprecated MYSQL functions, as 1.2 supports MYSQLI

I have just checked my sites that have nested snippets, all of them work as expected. An example: I use "IF" in combination with Ditoo for IDs and other conditionals - all work perfectly OK

**Comment by vinelandit** [comment] 2016-12-09 16:24
Hi modxuser, thanks for your reply. No, the custom snippets in question don't make any database calls. 

Can you confirm that switching your cached [[Ditto? ... ]] call for a cached [!Ditto? ... !] call still works?

**Comment by Deesen** [comment] 2016-12-09 18:07
`[!Ditto!]` still works for me testing the demo-page with blog, see screenshots. But inside ditto-tpl there is a uncached `[!Jot!]` which will be outputted for me like

![uncached1](https://cloud.githubusercontent.com/assets/8569221/21059389/755fa916-be42-11e6-8b64-93c960b77efc.png)

![uncached2](https://cloud.githubusercontent.com/assets/8569221/21059417/909b4c26-be42-11e6-9755-cb6eace668bb.png)

**Comment by modxuser** [comment] 2016-12-09 19:06
I have since updated my nested "IF" calls with the new built-in modifiers, but changing the Ditto snippet call from cached to uncached doesn't make any difference, it all still works.

**Comment by yama** [comment] 2016-12-10 00:10
@vinelandit Thank you for your information, I will fix it later

**Comment by dmi3yy** [comment] 2016-12-13 13:32
http://take.ms/oPgO7

This all ok
http://take.ms/pi8zW

But if change to [[Ditto not work (((

need normal work:
[[ [[
[! [!
[[ [!
[! [[

**Comment by yama** [comment] 2016-12-13 21:35
```
&year=`[[date_filter? &type=`year`]]`
```
This call will not work. Because it can not recognize the value nest. As with programming with PHP, you need to use different quotes.
```
&year="[[date_filter? &type='year']]"
```
For example, write like this.
By changing the specification like this, it is now possible to include characters such as " = ? & ` " in the value.
But it may be improved further. I will think about it.

**Comment by dmi3yy** [comment] 2016-12-13 21:53
But all this work on 1.1 
Its work from 1.0.9 or 1.0.8 

And this big problem for update. 

Need or fixed or write what need do. 




Отправлено с iPhone

**Comment by yama** [comment] 2016-12-13 23:49
ok, I will fix it later

**Comment by dmi3yy** [comment] 2016-12-14 12:19
with [[ [[ work 

but  with  [! [! still not work 

http://take.ms/SWPXS

but i newer used [! [! 

i think now all ok and can close

**Comment by MrSwed** [comment] 2016-12-15 12:58
@yama 
after update get "Nesting level too deep"
Where, on the older version works without problems ..

10 is not too small?

**Comment by MrSwed** [comment] 2016-12-15 13:22
Comment like 
```
[[ [[AjaxSearch? &showResults=`0` &showInputForm=`1` &ajaxSearch=`0` &ajaxSearchType=`0` &extract =`0` &landingPage=`33` &moreResultsPage=`33` &liveSearch=`0` &extract=`1` &advSearch=`allwords` &maxWords=`10` &minChars=`10`]]
]]
```
not work more - give error **"Nesting level too deep"**

**Comment by yama** [comment] 2016-12-15 13:37
> 10 is not too small?

It's possible, but it is maybe bug. Wait a moment.

**Comment by yama** [comment] 2016-12-15 13:40
```
while($delim==='`' && substr(trim($_tmp),0,1)!=='&' && trim($_tmp)!=='' && 1<substr_count($_tmp,'`')) {
    list($inner, $outer, $_tmp) = explode('`', $_tmp, 3);
    $value .= "`{$inner}`{$outer}";
    $i++;
    if(10<$i) exit('Nesting level too deep');
}
```
maybe fix

**Comment by MrSwed** [comment] 2016-12-15 13:46
it's kind of helped ..

**Comment by MrSwed** [comment] 2016-12-15 13:50
immediately I do not quite understand this block, but in the call the snippet may be missing **`** in values, and settings can  be **&** and **&amp;**

**Comment by yama** [comment] 2016-12-15 22:46
```
[[ [[AjaxSearch? &showResults=`0` &showInputForm=`1` &ajaxSearch=`0` &ajaxSearchType=`0` &extract =`0` &landingPage=`33` &moreResultsPage=`33` &liveSearch=`0` &extract=`1` &advSearch=`allwords` &maxWords=`10` &minChars=`10`]]
]]
```
Question. How does this work? I thought it was a magical snippet call.

**Comment by MrSwed** [comment] 2016-12-16 05:45
here is meant commented out
Of course you can not do so personally, I usually do something like
[[AjaxSearch-off ... ]]

**Comment by yama** [comment] 2016-12-16 07:44
Comment out? That's an interesting idea.
ok, I will fix it later.

**Comment by yama** [comment] 2016-12-16 08:00
https://github.com/modxcms/evolution/commit/7a2d6304cd693cc8d03fc85b62e2fdca96e8dd73
ok?

**Comment by MrSwed** [comment] 2016-12-19 10:42
new trouble:
```
[[if? &is=`[*articles_ids*]:!empty`
&then=`
<!-- skipped -->
[[Ditto? &documents=`[*articles_ids*]` &tpl=`articlesTpl` &orderBy=`pub_date DESC,createdon desc` &paginate=`0` &display=`all`]]
<!-- skipped -->`
]]
```
after update MODX get  "Illegal value of... "
1. If call ditto twice like phx ?

2. may be here (https://github.com/modxcms/evolution/blob/21fabe6d52befcda3646b90dd9c6b3524711035c/assets/snippets/ditto/classes/ditto.class.inc.php#L595)
be better somesthing like
```
  if(!preg_match('@^[0-9, ]*$@',$IDs))   return array();
```

**Comment by yama** [comment] 2016-12-19 11:12
```
[[if? &is=`[*articles_ids*]:!empty`
&then=`
    [[Ditto? &documents=`[*articles_ids*]` &orderBy=`editedon asc`]]
]]
```
Easily rewritten and tried it, but the problem did not happen. Are there other hints?

**Comment by yama** [comment] 2016-12-19 11:19
```
[[if? &is=`[*articles_ids*]:!empty`
    &then=`[[Ditto? &documents=`[*articles_ids*]`]] `
]]
```
Does this reproduce the problem?

**Comment by MrSwed** [comment] 2016-12-19 13:44
when I delete accidentally nonessential (skiped) deleted  tilde
so that nothing significant has changed
below is full snipped
```
[[if? &is=`[*articles_ids*]:!empty`
&then=`
<div id="Obzori">
	<hr>
	<div class="items">
[[Ditto? &documents=`[*articles_ids*]` &tpl=`articlesTpl` &orderBy=`pub_date DESC,createdon desc` &paginate=`0` &display=`all`]]
	</div>
</div>
`
&else=`<div id="Obzori"></div>`
]]
```
the problem temporarily solved the method proposed above (return array() instead exit

**Comment by yama** [comment] 2016-12-19 21:10
Is it related to the nesting of snippet calls?

**Comment by MrSwed** [comment] 2016-12-20 07:08
I think yes, snippet [[If]] should not call nested Ditto, if the condition does not match

**Comment by Deesen** [comment] 2016-12-20 07:21
But snippet-rendering works recursive from inside to outside, means "snippetIn" will always be rendered before snippetOut to provide a result (for example when using &param=[[ultimateParent]] you need a result first).

    [[snippetOut? &param=`[[snippetIn]]`]]

To get around this &param must be able to accept a chunk with snippetIn inside, which will only get parsed by snippetOut if true.

    [[if? &is=`1:is:1` &then=`@TPL:snippetIn_chunk`]]

**Comment by MrSwed** [comment] 2016-12-20 08:25
I think in this case it is necessary to solve both ways
1. Fix Ditto
2. Fix nested calls

**Comment by yama** [comment] 2016-12-20 10:19
https://github.com/modxcms/evolution/blob/90d3cdcdb5274d11ddc4fd6bd9636ee33085e0d2/manager/includes/document.parser.class.inc.php#L932-L937
Maybe these lines are unnecessary. Because nest processing is done in $modx->getParamsFromString() .

**Comment by yama** [comment] 2016-12-21 01:43
[document.parser.class.inc.zip](https://github.com/modxcms/evolution/files/665271/document.parser.class.inc.zip)
Maybe fixed

**Comment by yama** [comment] 2016-12-24 08:13
https://github.com/modxcms/evolution/commit/660163db2f2e1867e24ed109baef6ecb976e4021
Fixed now. Since there are many repair lines, please test carefully.

**Comment by yama** [comment] 2016-12-26 10:23
Found new pattern
```
[[if?
    &is=`1:not:2`
    &then=`
        [[if? &is=`1:not:3` &then=`
            [[if? 
                &is=`1:is:4` 
                &then=`aaa`
            ]]
        `]]
    `
    &else=`bbb`
]]
```
Not work

**Comment by dmi3yy** [comment] 2016-12-26 10:26
test this:

[[if?
    &is=`1:not:2`
    &then=`
        [[if? &is=`1:not:3` &then=`
            [[if?
                &is=`1:is:4`
                &then=`aaa`
&else=`ccc`
            ]]
        `]]
    `
    &else=`bbb`
]]

От 26 декабря 2016 г. в 12:23:23, yamamoto (notifications@github.com)
написал:

[[if?
    &is=`1:not:2`
    &then=`
        [[if? &is=`1:not:3` &then=`
            [[if?
                &is=`1:is:4`
                &then=`aaa`
            ]]
        `]]
    `
    &else=`bbb`
]]

**Comment by yama** [comment] 2016-12-26 10:36
It's work.
But, remove "&else=\`ccc\`” will malfunction

**Comment by dmi3yy** [comment] 2016-12-26 10:37
if not use ccc.  nothing to show )


От 26 декабря 2016 г. в 12:36:22, yamamoto (notifications@github.com)
написал:

It's work.
But, remove "&else=`ccc`” will malfunction

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1089#issuecomment-269198184>,
or mute the thread

**Comment by yama** [comment] 2016-12-26 10:39
In fact, a broken character string "aaa\`]]\`]] "is output. I think this is a malfunction of parser.

**Comment by Deesen** [comment] 2017-01-01 13:22
What is the issue? For me it seems to be working correct. I get result "bbb" for

	[[if?
		&is=`1:not:2`
		&then='
			[[if? &is=`1:not:3` &then=`
				[[if? 
					&is=`1:is:4` 
					&then=`aaa`
					&else=`bbb`
				]]
			`]]
		'
		&else=`ccc`
	]]

**Comment by dmi3yy** [comment] 2017-03-13 11:46
before update 
[[Ditto? &tpl=`chunk`]] and in chunk multiTV with @CODE. work correct 
http://take.ms/PPvzI


after update to last version on git  not work

**Comment by yama** [comment] 2017-03-23 12:37
```
[[if?
    &is=`1:not:2`
    &then='
        [[if? &is=`1:not:3` &then=`
            [[if? 
                &is=`1:is:4` 
                &then=`aaa`
                &else=`bbb`
            ]]
        `]]
    '
    &else=`ccc`
]]
```
Is this a code that does not work?

**Comment by dmi3yy** [comment] 2017-03-23 12:54
Tested all ok 
`[!if? &is=`1:not:2`
&then=`
	[!if? &is=`1:not:3` 
	&then=`
    	[!if?  &is=`1:not:4`  
		&then=` 
			[!if? &is=`1:is:4` 
			&then=`aaa`
			&else=`yes`
			!]`
        &else=`bbb` 
		!]`
    !]` 
&else=`ccc`
!]
<br>
[[if? &is=`1:not:2`
&then=`
	[[if? &is=`1:not:3` 
	&then=`
    	[[if?  &is=`1:not:4`  
		&then=` 
			[[if? &is=`1:is:4` 
			&then=`aaa`
			&else=`yes`
			]]`
        &else=`bbb` 
		]]`
    ]]` 
&else=`ccc`
]]
<br>
[!if? &is=`1:not:2`
&then=`
	[[if? &is=`1:not:3` 
	&then=`
    	[!if?  &is=`1:not:4`  
		&then=` 
			[[if? &is=`1:is:4` 
			&then=`aaa`
			&else=`yes`
			]]`
        &else=`bbb` 
		!]`
    ]]` 
&else=`ccc`
!]
<br>
[[if? &is=`1:not:2`
&then=`
	[!if? &is=`1:not:3` 
	&then=`
    	[[if?  &is=`1:not:4`  
		&then=` 
			[!if? &is=`1:is:4` 
			&then=`aaa`
			&else=`yes`
			!]`
        &else=`bbb` 
		]]`
    !]` 
&else=`ccc`
]]
<br>
[[if? &is=`1:not:2`
&then=`
	[!if? &is=`1:not:3` 
	&then=`
    	[!if?  &is=`1:not:4`  
		&then=` 
			[[if? &is=`1:is:4` 
			&then=`aaa`
			&else=`yes`
			]]`
        &else=`bbb` 
		!]`
    !]` 
&else=`ccc`
]]
<br>
[!if? &is=`1:not:2`
&then=`
	[[if? &is=`1:not:3` 
	&then=`
    	[[if?  &is=`1:not:4`  
		&then=` 
			[!if? &is=`1:is:4` 
			&then=`aaa`
			&else=`yes`
			!]`
        &else=`bbb` 
		]]`
    ]]` 
&else=`ccc`
!]`
on old parser 
yes 
yes 
yes 
aaa 
yes 
aaa

on new parser 

yes 
yes 
yes 
yes 
yes 
yes

**Closed** 2017-03-23 12:58 UTC
Labels: 1.2.2
