### ISSUE TITLE
YAMS and 1.2.1RC not working correct

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1154] opened 2016-12-28 14:48 UTC
On a clean install 1.2.1RC I have installed YAMS.
Some snippet calls didn't work.
```[[YAMS? &get=`repeat` &repeattpl=`vlagTpl` &currenttpl=`vlagTplcurrent`]]```

Output was empty.
After downgrading to 1.2 it started to work again!

**Comment by dmi3yy** [comment] 2016-12-29 01:05
can you send me access to site  i was test

**Comment by fourroses666** [comment] 2016-12-30 13:48
You both have access @dmi3yy @yama 
PM in Slack.

**Comment by fourroses666** [comment] 2016-12-30 17:29
@Deesen 
Does YAMS work for you on 1.2.1RC ?

**Comment by Deesen** [comment] 2016-12-30 18:36
Well I don´t understand what exactly is going on but xdebug reveals the first parameter gets modified by YAMS. The params of snippet-call

    [[YAMS? &get=`repeat` &repeattpl=`vlagTpl` &currenttpl=`vlagTplcurrent`]] 

will result in an array like

    $modx->event->params = array (
      '(yams-select:17)(lang:17:en)get' => 'repeat',
      'repeattpl' => 'vlagTpl',
      'currenttpl' => 'vlagTplcurrent',
      '(/yams-select:17)' => '',
    )

Means the YAMS get-param is not given/empty which will cause the snippet to show nothing. Need to investigate more the root cause..

**Comment by Deesen** [comment] 2016-12-30 18:39
Ah I forgot, logically you can get around the bug for the time being with

    [[YAMS? &buggedFirstParam=`xxx` &get=`repeat` &repeattpl=`vlagTpl` &currenttpl=`vlagTplcurrent`]]

**Comment by fourroses666** [comment] 2016-12-30 18:48
Just for the record; Wayfinder isn't working as well.

```[!Wayfinder? 
&buggedFirstParam=`xxx`
&startId=`0` 
&level=`1` 
&removeNewLines=`1`
&rowTpl=`@FILE:assets/modules/yams/tpl/wayfinder/docr/row.tpl`
!]```

**Comment by Deesen** [comment] 2016-12-30 19:15
Without 

    &rowTpl=`@FILE:...`

Wayfinder works again..

**Comment by fourroses666** [comment] 2016-12-30 19:17
Yea I know, but then Wayfinder isn't multilang. :-(

**Comment by Deesen** [comment] 2016-12-30 19:22
I meant as info for @yama .. something strange is going on here and I think it has to do with documentParser.

**Comment by Deesen** [comment] 2016-12-31 12:30
@yama I found the responsible line. If I comment out https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1496 then YAMS works again.

**Comment by yama** [comment] 2016-12-31 15:01
Happy new year 2017 just now, in Japan

@Deesen 
Thanks. I also think that this line is unnecessary. But, removing this line causes problems with the evoBabel plugin.
The OnParseDocument event is confusing in various plugins implementations, such as PHx elsewhere.
I will consider something good.

**Comment by yama** [comment] 2016-12-31 15:08
https://github.com/webber12/evobabel-0.2/blob/2963f49c2db34b197fd5b3e787d16b49cac41c06/install/assets/plugins/plugin.evoBabelPlaceholders.tpl

**Comment by yama** [comment] 2017-01-01 04:13
```
    function getParamsFromString($string='')
    {
        if(empty($string)) return array();
        
        if(strpos($string,'&_PHX_INTERNAL_')!==false) // For PHx plugin
            $string = str_replace(array('&_PHX_INTERNAL_091_&','&_PHX_INTERNAL_093_&'), array('[',']'), $string);
        
        if(strpos($string,'[%')!==false) { // For evoBabelPlaceholder plugin
            $_ = $this->documentOutput;
            $this->documentOutput = $string;
            $this->invokeEvent('OnParseDocument');
            $string = $this->documentOutput;
            $this->documentOutput = $_;
        }
```
temporary fix, maybe

**Comment by Deesen** [comment] 2017-01-01 12:16
Happy new year to you too!

Yes, looks like it should work like this but is it really good to add such special plugin-related checks into documentParser? I think maybe this makes more sense?

- a new plugin-event like "OnParseParamsFromString"
- or something like `$modx->pluginEventPosition`

            $this->pluginEventPosition = 'getParamsFromString';      // New variable
            $_ = $this->documentOutput;
            $this->documentOutput = $string;
            $this->invokeEvent('OnParseDocument');
            $string = $this->documentOutput;
            $this->documentOutput = $_;
            $this->pluginEventPosition = '';

So we could change YAMS / EvoBabel-plugin to use a new event, or use $this->pluginEventPosition so plugins can determine if parsing should be applied or skipped.

**Comment by yama** [comment] 2017-01-02 09:42
@Deesen 
If updating to evo 1.2.1, is it also updating evoBabel at the same time? If so, I think that is a smart solution.
I always think. Plugins should compensate for missing functions in the core. However, I think that it is not good for a specific plugins to hinder core evolution.
The OnParseDocument event is not good. When plugin like PHx were born, we should have prepared system events carefully.

**Comment by yama** [comment] 2017-01-02 09:46
Another idea that I thought was to create a "legacy mode" as a mode of parse and make it selectable by config. If you choose this setting, tags are separated with regular expressions like old Evo.
```
$modx->config['parser_mode']='legacy' // modern or legacy
```

**Comment by Deesen** [comment] 2017-01-02 14:04
What do you mean by "is it also updating EvoBabel at the same time"? I don´t know if there is any auto-updater taking care of EvoBabel, if you mean that. I guess not. Maybe instead of adding "custom code" to documentParser like for "EvoBabel" we could add such a check to the install-procedure, to inform users before updating that "EvoBabel" (and maybe PHX etc) require an update too.

Personally I think a new event like "OnParseParams" is the most "forward-looking" solution especially for allowing plugins like EvoBabel replacing custom placeholders like [%ph%].

**Comment by dmi3yy** [comment] 2017-01-02 14:17
If all ok in parser we can publish 1.2.1  but write about Yams And EvoBabel need update to. No see problem

Отправлено с iPhone

**Comment by Deesen** [comment] 2017-01-02 14:46
Problem is YAMS does not work with https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1496

What do you think about new event "OnParseParams" for this purpose?

**Comment by Deesen** [comment] 2017-01-02 16:56
Then we just have to add "OnParseParams" to case "OnParseDocument" at https://github.com/webber12/evobabel-0.2/blob/master/install/assets/plugins/plugin.evoBabelPlaceholders.tpl#L19

**Comment by dmi3yy** [comment] 2017-01-03 11:43
But on earlier version all work fine :)

now need or fix  or write in all extras like   evobabel Yams + write in realise notes about this. 

all another for 1.2.1 ready and we can publish after close this issues

**Comment by Deesen** [comment] 2017-01-03 11:56
I think we just need to decide which option is most professional and "forward-looking" into the future:

a) replace OnParseDocument by new event OnParseParams https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1496
b) add `$modx->pluginInvokeSource = 'getParamsFromString'` so inside YAMS-plugin etc we can optionally check for `$modx->pluginInvokeSource`
c) `$modx->config['parser_mode']='legacy' // modern or legacy` to optionally enable/disable https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1496

I think a) is perfect.

**Comment by dmi3yy** [comment] 2017-01-04 10:51
Deesen can you write press realise for 1.2.1 ?

**Comment by Deesen** [comment] 2017-01-04 13:48
Yes no problem, but what about this issue here?

**Comment by Deesen** [comment] 2017-01-05 10:00
@fourroses666 It should be fixed now and needs some testing with evobabel before merging. But YAMS should work https://github.com/Deesen/evolution

**Comment by fourroses666** [comment] 2017-01-05 10:17
Nice D, so I don't need to check the new plugin-event for YAMS?
I have never used evoBabel. Maybe @dmi3yy can test it?

**Closed** 2017-01-06 15:51 UTC
Labels: 1.2.1
