### ISSUE TITLE
TinyMCE4 use custom styles / need settings on 1 place

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1134] opened 2016-12-21 15:07 UTC
With tinymce3 it was possible to use custom styles.
I thought this was possible in tinymce4 too.
When I add this on config > interface tab settings nothing happens.

When using Options I keep seeing Title 1 / Title 2

![config-t4](https://cloud.githubusercontent.com/assets/523389/21394091/719d6dd2-c797-11e6-9ca0-ea823470fed6.jpg)
![manager-t4](https://cloud.githubusercontent.com/assets/523389/21394090/719b7216-c797-11e6-9b9e-1c1ffa7b53d5.jpg)

**Comment by fourroses666** [comment] 2016-12-21 15:13
Its at Plugin Configuration Tab TinyMCE4

**Comment by fourroses666** [comment] 2016-12-21 15:24
@dmi3yy need to remove Block Formats (and more settings) from config or plugin settings.

Block Formats doesn't work on Config > Interface tab.

**Comment by bossloper** [comment] 2016-12-28 11:51
Block format from the config seems to work for me.
For example:
I have 'Theme' = 'MODX Style'
I customised block formats: 'Block Formats' = 'Para=p;First Head=h1;Second Head=h2'

![untitled](https://cloud.githubusercontent.com/assets/1744687/21521331/e8706250-ccf3-11e6-8b90-efd3122a9ca0.png)

**Comment by fourroses666** [comment] 2016-12-28 13:44
hmm, maybe because of a custom theme or its fixed.

**Comment by bossloper** [comment] 2016-12-28 14:47
Probably the custom theme does not have the plugin

**Comment by risingisland** [comment] 2016-12-28 15:19
You can edit this directly in the Plugin config., under Style Formats...

![cms manager](https://cloud.githubusercontent.com/assets/6113504/21524812/f7d81bbc-cd10-11e6-93a7-7d8257d2f11d.png)

**Comment by fourroses666** [comment] 2016-12-28 16:02
Yes I know. 

So the block formats field on the config page > interface tab can be removed.

**Comment by Deesen** [comment] 2016-12-28 16:32
LOL.. I know now what is going on... @fourroses666 Please check in your admins user-settings, there you can also set these blockFormats which will be accessible by this button. I guess a checkbox like "use global settings" is missing for some settings.

![tiny](https://cloud.githubusercontent.com/assets/8569221/21526299/77a7ecf2-cd23-11e6-8e35-221683b265be.png)

**Comment by fourroses666** [comment] 2016-12-28 16:48
Where are these "admins user-settings"? 

_I know I can add these settings on the TinyMCE4 > Plugin tab > Config > Custom Style Formats
That works but for me the Usage > Config > Interface & options > Block Formats don't work._

**Comment by Deesen** [comment] 2016-12-28 17:17
I meant Security -> Manager Users -> Edit your "Admin User" -> Tab "User" and scroll to bottom

**Comment by risingisland** [comment] 2016-12-28 17:34
Yeah, the Theme and Skins has a Use global settings, but not the Block elements...

![xx](https://cloud.githubusercontent.com/assets/6113504/21527502/a4ff283c-cd23-11e6-9bed-ef04083842a1.png)

**Comment by bossloper** [comment] 2016-12-28 17:42
Which theme is running? I think 'custom' by default does not have the plugin that shows the paragraph formats.

**Comment by risingisland** [comment] 2016-12-28 17:46
I think most include it, and if it is custom, you can just add it to the Custom plugins and buttons row.

**Comment by Deesen** [comment] 2016-12-28 17:51
I tested with "full"-theme.

**Comment by bossloper** [comment] 2016-12-29 10:49
I suggest changing the default TinyMCE4 plugin configuration value for 'Custom Style Formats'.
As they are 'Title1','Title2' it suggests they could be block formats, whereas they are not, they are spans.
Maybe set to something like:

CustomStyle1,cssClass1|CustomStyle2,cssClass2|CustomStyle3,cssClass3

**Comment by terrybarth** [comment] 2016-12-29 20:35
I'm trying to figure this out as well.  Now that I have the custom styles working, I need to change the html output to add the class to the selected tag instead of inserting spans into everything.  If I'm understanding this correctly, this is referenced in the documentation under the content formatting-->formats--examples of usage:  https://www.tinymce.com/docs/configure/content-formatting/

However, I cannot figure out how to implement this in Modx.

**Comment by Deesen** [comment] 2016-12-30 05:33
Maybe https://www.tinymce.com/docs/configure/content-formatting/#style_formats -> MODX TinyMCE4-Plugin -> Param "Custom Style Formats" .

All of these TinyMCE-themes have the required "styleselect"-button: legacy, creative, full, advanced and logic.

**Comment by terrybarth** [comment] 2016-12-30 14:38
First thing I tried. It caused the plugin to fail. Had I not made a copy of the plugin, I would've had to reinstall the plugin. Perhaps I didn't enter it correctly.

**Comment by terrybarth** [comment] 2016-12-31 17:22
I have a client that really needs these style pull downs, but I'll have to rework my style sheet to make them work with spans and I really don't want all the unnecessary code it would generate.

Is there no way to implement these custom style formats within Modx that add classes directly to the tags vs adding spans? 

Is there an alternative editor I need to use?

**Comment by Deesen** [comment] 2017-01-01 12:35
Please explain in detail on which tags you want to apply which classes? I mean 1-2 examples like `"Label": tag.class` so I can try to find a solution.

- "Outer Wrap": div.container
- "Well": div.well

**Comment by terrybarth** [comment] 2017-01-02 00:39
Thank you so much for the help.  Here are a couple of examples.

"Image Left":img.imagleft
"Image right":img.imageright
"Blue Button";h2.blue-button

Previously these styles could be applied to any element not just those specified. So the Blue Button could be applied to a div, p, h1, etc without specifying them in advance.

I would have defined those in the custom styles config likes this.

Image Left=imageleft;Image Right=imageright;Blue Button=blue-button

**Comment by Deesen** [comment] 2017-01-02 05:38
I guess what you need is this kind of setup using a comma-separated "selector"-list (like for h1,h2,h3 etc) or wild-card * to apply to all tags. You need to copy/paste from [ to ] to avoid errors:

    [
      {title: 'Image Left',  selector: 'img', classes: 'imagleft'},
      {title: 'Image Right', selector: 'img', classes: 'imagright'},

      {title: 'Blue Button H1, H2', selector: 'h1,h2', classes: 'example1'},
      {title: 'Blue Button ALL',    selector: '*',     classes: 'example2'}

    ]

BTW, for images there is a special parameter to set classes for the select-box inside image-window: https://www.tinymce.com/docs/plugins/image/#image_class_list

**Comment by terrybarth** [comment] 2017-01-02 15:25
Right, so I pasted this example into the custom formats parameter, bracket to bracket. When I go to edit a page there is no rich text editor at all.  This is what I tried early on, but I assumed that perhaps I had the wrong syntax or something.

Does this work for you?

Thanks for hanging in there with me on this.

**Comment by Deesen** [comment] 2017-01-02 15:54
Yes it works for me

![styles](https://cloud.githubusercontent.com/assets/8569221/21592224/0e524bca-d10c-11e6-9605-e603a712501d.png)

**Comment by terrybarth** [comment] 2017-01-02 17:06
Hmmm, I made a duplicate of the TinyMCE4, then edited the configuration like this:

![tinymce_-_content_formatting](https://cloud.githubusercontent.com/assets/526281/21593273/04e51eb8-d0db-11e6-9733-3cb5704dafb8.png)

I'm running Modx Evo 1.2, php version 5.5.38

I would be happy to give you a login to see this directly.

**Comment by bossloper** [comment] 2017-01-02 17:20
The custom style needs to include 'style_formats'. So it should be:

```
style_formats: [
  {title: 'Image Left',  selector: 'img', classes: 'imagleft'},
  {title: 'Image Right', selector: 'img', classes: 'imagright'},

  {title: 'Blue Button H1, H2', selector: 'h1,h2', classes: 'example1'},
  {title: 'Blue Button ALL',    selector: '*',     classes: 'example2'}
]
```

**Comment by Deesen** [comment] 2017-01-02 17:24
Sorry no, your explanation fits to "custom parameters". There you would have to add "style_format:". But not in custom styles. My working configuration with latest 1.2.1dev looks like

![styles2](https://cloud.githubusercontent.com/assets/8569221/21593548/9b62f918-d118-11e6-8521-4b01f011ba5f.png)

**Comment by Deesen** [comment] 2017-01-02 17:29
@terrybarth If you duplicate TinyMCE you should not have more than 1 of them active. You screenshot shows 2 active ones. Maybe this is the issue?

**Comment by terrybarth** [comment] 2017-01-02 17:34
Yes! That was the issue. Good grief. . .  Sharp eyes.

Thank you so much for your help.

**Comment by bossloper** [comment] 2017-01-02 17:36
@Deesen - yes sorry I meant custom params. Though I guess either works.

**Comment by bossloper** [comment] 2017-01-02 17:50
@Deesen - do you think we need the 'Custom Style Formats' for TinyMCE4 - as it is an unusual mix of either a 'MODX specific' simple syntax (which is quite restricted and I would suspect in the real world little used) or using TinyMCE syntax. With the custom formats in TinyMCE4 being slightly more complex than TinyMCE3 could we just use the Custom Params which is purely TinyMCE syntax and so just refer to the TinyMCE help pages?

**Comment by terrybarth** [comment] 2017-01-02 18:19
Personally, I use the custom style formats on almost all of my sites to enable clients to add buttons, float images, choose a brand color, etc. In the previous versions of TinyMCE I could simply provide the style name and the class name like this:

Image Left=imageleft;Image Right=imageright;Blue Button=blue-button

This applied the style directly to any tag without all the extra spans. The TinyMCE custom formats are more selective/powerful/complex, but I've never needed this level of specificity.

Perhaps a configuration field could be used to accept this simple format then translate it into the TinyMCE4 format behind the scenes? If someone really needs more selective control, they could still use the standard TinyMCE4 format.

It seems to me, just pointing to the TinyMCE documentation doesn't really tell you how to do this within Modx, hence this long discussion.

**Comment by bossloper** [comment] 2017-01-02 18:26
The problem is because TinyMCE4 is more powerful the simple syntax from TinyMCE3 cannot be easily translated to cover all possibilities. i.e. 
'sometext=cssformat' in TinyMCE3 would automatically appy a format to the heading tags or if a whole paragraph was selected then it would apply to the p tag **automatically**. TinyMCE4 does not seem to work like that and custom styles need to be defined specifically for tags/blocks etc... unless someone knows otherwise?

**Comment by terrybarth** [comment] 2017-01-02 18:54
Perhaps the default value/example in the custom parameters field might be helpful with a link back to the official documentation?

style_formats: [
  {title: 'Image Style 1',  selector: 'img', classes: 'imagstyle1'},
  {title: 'Heading H1, H2', selector: 'h1,h2', classes: 'heading1'},
  {title: 'Heading ALL',    selector: '*',     classes: 'heading2'}
]

**Comment by bossloper** [comment] 2017-01-02 19:01
Potentially yes IMO. Which asks the question; then does the 'custom style' field have any value, or does it just add confusion and need removing?

**Comment by terrybarth** [comment] 2017-01-02 19:15
Based on on how this works in TinyMCE4, I would never use the custom style format because of what it does to the code (insert spans).  So I would agree, remove it.

Of course, there must have been some reason TinyMCE changed this in version 4. Perhaps my use is not typical? Perhaps most Modx folks would want the native TinyMCE behavior as designed?

**Comment by bossloper** [comment] 2017-01-02 19:19
... not sure, I prefer the TinyMCE3 logic.

**Comment by terrybarth** [comment] 2017-01-02 19:27
Yep, I prefer the TinyMCE3 approach as well.

**Comment by pmfx** [comment] 2017-01-02 20:03
Actually I like the new TinyMCE4 "Formats" logic. It's more complex, powerful and with selectors it gives us more control over content css classes. No more clients sticking image classes to paragraphs etc. I like it! As for example configuration, perhaps it should look similar to what Deesen and terrybarth showed.

**Comment by Deesen** [comment] 2017-01-02 20:35
@bossloper If you remember #886 there is also a "simple format" which we changed with https://github.com/modxcms/evolution/commit/5733ccad74aba8b15c526a0c3c45dca720a640b0 . This is the "advantage". And if you set "selector:*" then you have the old TinyMCE3-logic as far as I understood.

What about adding a new parameter like "formatselect-type" below "custom style formats" which will control how a string in simple-format like `Title1,class1|Title2,class2` will be used within TinyMCE: 

- inline: span
- selector: *
- selector: a,strong,em,p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,tr,span,img (old code just as example)

**Comment by bossloper** [comment] 2017-01-02 21:10
"selector:*" does not emulate TinyMCE3 exactly. If you select all text in a paragraph, or place cursor in a header and add a custom style it will not add that style to the paragraph/header tag as a class.

**Comment by Deesen** [comment] 2017-01-03 05:25
Plus we could transform simple format like `Title1,class1|Title2,class2` into subcategories:

      [
       {title: 'Inline', items: [
         {title: 'Title1', inline: 'span', classes: 'class1'},
         {title: 'Title2', inline: 'span', classes: 'class2'}
       ]},

       {title: 'Blocks', items: [
         {title: 'Title1', selector: '*', classes: 'class1'},
         {title: 'Title2', selector: '*', classes: 'class2'}
       ]}
      ]

**Comment by bossloper** [comment] 2017-01-04 09:20
Yes that seems a good compromise. For less technical editors they may be confused by the terms 'inline' and 'block' but that is a minor point and probably fine as is. It could have a set of 'real-world' defaults to give a good starting point for setting a site up.

**Comment by Deesen** [comment] 2017-01-04 09:44
Glad you like it. But which "real-world"-defaults do you have in mind that make sense for inline and block? Align-left, align-right, full-width for example?

**Comment by bossloper** [comment] 2017-01-04 10:07
To keep things simple I prefer to override the toolbar alignment buttons with a class rather than creating additional custom block formats:
`
formats : {
alignleft   : {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img,iframe', classes : 'justifyleft'},
alignright  : {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img,iframe', classes : 'justifyright'},
alignfull   : {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img,iframe', classes : 'justifyfull'},
aligncenter   : {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img,iframe', classes : 'justifycenter'}
}
`
... so no at the moment I cannot think of a useful generic block format example!

**Comment by fourroses666** [comment] 2017-01-06 15:53
I lost track a bit. Can I close this or still have to make a decision about the defaults?

**Comment by bossloper** [comment] 2017-01-06 17:35
Don't think it is quite done yet. There may potentially be a new custom format field so there is one for inline styles and one for block styles...

**Comment by Deesen** [comment] 2017-01-06 18:45
Right, I will do tomorrow..

**Comment by Deesen** [comment] 2017-01-07 05:35
This 

![styles5-2](https://cloud.githubusercontent.com/assets/8569221/21739714/55cccd1e-d4a3-11e6-83ad-c09f3d13e864.png)

will turn into a inline/block separated list

![styles5](https://cloud.githubusercontent.com/assets/8569221/21739716/5f4ec86a-d4a3-11e6-936c-5a47b900a6ee.png)

**Comment by bossloper** [comment] 2017-01-09 09:43
Tested. Works well... thanks!

**Comment by bossloper** [comment] 2017-01-13 13:58
@fourroses666 - do you want to close this now? Think it is all fixed.

**Closed** 2017-01-13 16:49 UTC

**Comment by Deesen** [comment] 2017-01-27 08:47
Improved plugin-config and added some more detailed explanation as this parameter seems to lead to confusion:

![tiny4-styleformats](https://cloud.githubusercontent.com/assets/8569221/22364967/4efa4462-e475-11e6-975a-3aab5c7e8aa0.png)
